apiVersion: v1
kind: Secret
metadata:
  name: casino-secrets
type: Opaque
data:
  # 'pierdeTuDinero.com' codificado en Base64
  DB_PASSWORD: cGllcmRlVHVEaW5lcm8uY29t
  # 'casino-vida-gerard-ivan' codificado en Base64
  JWT_SECRET: Y2FzaW5vLXZpZGEtZ2VyYXJkLml2YW4=